### ISSUE TITLE
Migrating `generate` to use MonadIO instead of IO?

### ISSUE THREAD

**Issue by theophile-scrive** [tfausak/heptapod#5]
Hi @tfausak, thanks again for Heptapod! 
I would like to know if you would be interested to use `MonadIO` instead of `IO` for `generate`. This is mostly for convenience when working with a transformer stack, or other effect systems.

Cheers!

**Comment by tfausak** [comment]
Great suggestion! Released in [version 1.1.0.0](https://github.com/tfausak/heptapod/releases/tag/1.1.0.0).

**Comment by theophile-scrive** [comment]
Fantastic, thank you so much!
